require 'ostruct'
require 'open-uri'
require 'hpricot'
require 'zip/zip'
require File.dirname(__FILE__) + '/tvdb/urls'
require File.dirname(__FILE__) + '/tvdb/client'
require File.dirname(__FILE__) + '/tvdb/serie'